### ISSUE TITLE
Update dependencies etc. after SDK rename

### ISSUE THREAD

**Issue by Jalle19** [UpCloudLtd/upcloud-packer#13] opened 2017-06-12 14:03 UTC
Since `upcloud-go-sdk` got renamed to `upcloud-go-api` this project will need some changes as well.

**Comment by Jalle19** [comment] 2018-04-03 07:29
Since the SDK got renamed again to `upcloud-go-api` this is still relevant

**Comment by maxfrei** [comment] 2021-02-15 13:36
The issue is out of date. Closing.

**Closed as completed by maxfrei** 2021-02-15 13:36 UTC
